import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";

import localFont from "next/font/local";
import "@/app/globals.css";

const lxgw = localFont({
  src: "./fonts/LXGWWenKai-Regular.woff2",
  variable: "--font-lxgw-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "运维平台",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lxgw.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
